apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.json
  - service.json
  - deployment.json
  - pod-disruption-budget.json
  - network-policy-default-deny.json
