apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../ok-shared-live

images:
  - name: ghcr.io/openkubes/ok-console
    newName: ghcr.io/openkubes/ok-console
    digest: sha256:dc98054b520bb89b4b8aae1b77e1da8ffa86bbdf359efbeb9e350caa3a79261b

patches:
  - path: deployment-breakglass.yaml
  - path: network-policy-breakglass.yaml
