apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../ok-shared-live

images:
  - name: ghcr.io/openkubes/ok-console
    newName: ghcr.io/openkubes/ok-console
    digest: sha256:705edc32be35c935d25414c790cc648649ab3aa3ace24f42423510e3a9e8ccbc

patches:
  - path: deployment-breakglass.yaml
  - path: network-policy-breakglass.yaml
